version: '3'

services:
    portainer:
        image: portainer/portainer
        container_name: portaniner-rpi
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

    mongo:
        image: johnrazeur/arm-mongo:latest
        container_name: mongo-rpi
        ports:
            - 27017:27017
        env_file:
            - env.mongo
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - mongo-data:/data/db

    mongo-express:
        image: ind3x/rpi-mongo-express
        container_name: mongo-express-rpi
        ports:
            - 8081:8081
        links:
            - mongo:mongo
        env_file:
            - env.mongoexpress

    postgresql:
        image: postgres:9
        container_name: pg-rpi
        ports:
            - 5432:5432
        env_file:
            - env.pg
        volumes:
            - db-data:/var/lib/postgresql/data

    pgadmin:
        image: biarms/pgadmin4
        container_name: pg-admin-rpi
        links:
            - "postgresql:pgsql-server"
        ports:
            - 5050:5050
        volumes:
            - pgadmin-data:/var/lib/pgadmin
               
    influxdb:
        image: influxdb
        container_name: influxdb-rpi
        ports:
            - 8086:8086
        env_file:
            - env.influxdb
        volumes:
            - influxdb-data:/var/lib/influxdb
                 
    grafana:
        image: grafana/grafana
        container_name: grafana-rpi
        links:
            - influxdb
        ports:
            - 3000:3000
        env_file:
            - env.grafana
        volumes:
            - grafana-data:/var/lib/grafana
            
    telegraf:
        image: telegraf:latest
        container_name: telegraf-rpi
        links:
            - influxdb
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
    portainer_data:
    db-data:
    pgadmin-data:
    mongo-data:
    influxdb-data:
    grafana-data:
